# conda env create -f environment.yml
name: owslib
channels:
  - conda-forge
dependencies:
  # notebook
  - jupyterlab
  - ipywidgets
  - nodejs
  # owslib
  - python-dateutil
  - pytz
  - requests
  - pyproj
  - lxml
  # birdy
  - click
  - jinja2
  - wrapt
  - funcsigs
  - boltons
  - pip:
    - -e git+https://github.com/bird-house/OWSLib.git@esgfwps#egg=owslib
    # - -e git+https://github.com/bird-house/birdy.git@master#egg=birdy
